name: CI

on:
  push:
    branches: [main]

jobs:
  test:
    name: Build and run tests
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
        with:
          path: live_state
      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: '25.1' # Define the OTP version [required]
          elixir-version: '1.14.0' # Define the elixir version [required]
      - name: Restore dependencies cache
        uses: actions/cache@v2
        with:
          path: live_state/deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-
      - uses: actions/cache@v1
        name: Cache build
        with:
          path: _build
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          path: live_state
      - name: Install dependencies
        run: mix deps.get
        working-directory: live_state
      - name: Run tests
        run: mix test
        working-directory: live_state
